### ISSUE TITLE
Include Lee-Carter models

### ISSUE THREAD

**Issue by MatthewCaseres** [actuarialopensource/pymort#16]
maybe it is like this? https://github.com/robjhyndman/demography/blob/master/R/lca.R

**Comment by jkoestner** [comment]
i've created a LeeCarter model here in python:

https://github.com/jkoestner/morai/blob/main/morai/forecast/models.py#L205

**Comment by MatthewCaseres** [comment]
Put a link to morai in the repo, closing this out, thanks
