### ISSUE TITLE
Validation of tables

### ISSUE THREAD

**Issue by MatthewCaseres** [actuarialopensource/pymort#2]
Users need confidence in their tables. I am unsure the best way to test this.

Manual testing can and should be done, but does not scale well.

Maybe MortalityTables.jl can serve as an independent source of verification over larger sets of tables? @alecloudenback? I can probably do this but help is welcome!

**Comment by alecloudenback** [comment]
MortalityTables.jl has the same concern - I've tried to test a variety of table formats. You can see the variety of things tested here: https://github.com/JuliaActuary/MortalityTables.jl/tree/master/test

We could utilize the same underlying test data though... e.g. gradually add tests to a CSV file with columns: `Table Name`, `Rate type (e.g. select or ultimate)`, `issue age`, `attained age`, `rate` and then load and test that file. In the next few weeks I could take a crack at a start of that and we could keep it in an github.com/actuarialopensource repository for different packages to reference (or other version controlled source that makes sense).

**Comment by MatthewCaseres** [comment]
Could PyCall.jl be used to compare that the mortality tables are the same for every single value between the two packages? I think if pymort == MortalityTables.jl then any errors distributed to users would be caused by us both making the exact same mistake.

Unsure how to implement this, but basically a function you can call that tests if our packages are distributing the exact same tables.

**Comment by alecloudenback** [comment]
I think that's not too difficult, but risks missing overlapping issues, e.g. both packages are incorrect on one of the nonstandard mortality tables like a projection scale table.

I'm also a little hesitant to add a dependecy between the packages in an automated test suite - e.g. if one package is broken then it would mean that tests don't pass for the other package.

I wasn't picturing that the CSV file would be very large, just pick `n` random tables and then some random points within that table.  Should be able to get very good coverage of the table universe with such a sample.

**Comment by MatthewCaseres** [comment]
Maybe these tests are in their own repo and not a dependency of either package? 

Testing consistency between packages will let me pin my package's reliability to your package, and perhaps something will be found. It feels kind of jank but being able to check every single value has some appeal.

I'll submit a PR related to the issue linked in your repo. I think the columns can be labeled as follows - 
| tableID | issueAge | duration | attainedAge |
| - | - | - | - |

**Comment by MatthewCaseres** [comment]
I believe the benchmarks have validated the parsing well enough. I have checked that all of the tables, even irregular ones are handled by our parsing logic. I believe this issue can be closed.
