### ISSUE TITLE
Update requirements to allow pandas 2.0

### ISSUE THREAD

**Issue by jkoestner** [actuarialopensource/pymort#24]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Description

With python packages starting to upgrade there may be deprecation warnings when staying on pandas 1.x.x. Could you loosen the requirements on packages?

### Problem

Python packages are stale

### Proposed Solution

Loosen the python package requirements. 

### Alternatives Considered

No

**Comment by MatthewCaseres** [comment]
fixed + merged, thanks for finding

**Comment by jkoestner** [comment]
Thanks - useful tool!
